version: "3.8"

services:

  api_project:
    container_name: api_project
    build:
      args:
        user: finn
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: travellist
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    env_file: ./.env
    links:
      - mysql
    networks:
      - finn
  
  api_serve:
    image: nginx:alpine
    container_name: api_serve
    depends_on: 
      - api_project
    links: 
      - api_project
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/api/nginx:/etc/nginx/conf.d/
    networks:
      - finn

  mysql:
    image: mysql:5.7.29
    container_name: mysql_laravel
    restart: unless-stopped
    tty: true
    environment: 
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    volumes: 
      - ./docker/mysql:/var/lib/mysql
    ports: 
      - ${DB_PORT}:3306
    networks:
      - finn

volumes:
  mysql_laravel:

networks:
  finn:
    driver: bridge
